# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94cd9137cdc166c0f0cf4dfc71255733fd333e012c487047379c30506a1ec15a83a7b998a45cb69bf75b526a1942d37d057785e3c520aa55fe356e7d04eef40d

test:
  secret_key_base: e00c4c4ad5a318fc26587a0293ded383e51a4897de89fe3a3eae420352e07f116b833fc373dec60d416bc3cf18bdbd23c5baf558c08f18b6a974800ae430494a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
